#!/bin/bash

mkdir -p dist
coffee -o lib -b -c src/*.coffee
pkg . --target node8-macos-x64 --output dist/map-digitizer-server
# Kind of a hack. We have to keep this with our executable
cp node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node dist
