#!/bin/bash
# Compile this server with "@zeit/pkg". This is kind of outclassed by Docker-based
# installation for portability, but it could still be valuable
mkdir -p dist
npm run prepublish
pkg . --target node8-macos-x64 --output dist/mapboard-server
# Kind of a hack. We have to keep this with our executable
cp node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node dist
