#!/usr/bin/env zsh

dn=${0:a:h}

# This is a hack that leaves us exposed to changes elsewhere
name=/Users/Daven/Development/Naukluft/versioned/tile-server

${dn}/node_modules/.bin/tessera --require @mapbox/mbtiles --port 3005 --config ${dn}/tile-config.json & PIDTILES=$!
node index.js & PIDSERVER=$!

wait $PIDTILES
wait $PIDSERVER
