#!/usr/bin/env zsh

dn=${0:a:h}

$(npm bin)/tessera --require tilelive-mapnik --port 3005 --config ${dn}/tile-config.json & PIDTILES=$!
coffee index.coffee & PIDSERVER=$!

wait $PIDTILES
wait $PIDSERVER
